use aliasc::{backend, compile_model, context::{DistroArg, EnvironmentArg, PlatformArg, Shell}, manifest, CompileOptions, Context};
use clap::{Args, Parser, Subcommand};
use std::{path::PathBuf, process::ExitCode};

#[derive(Parser)] #[command(name="aliasc", version, about="Alias DSL v2 compiler")]
struct Cli { #[command(subcommand)] command: Command }
#[derive(Subcommand)] enum Command { Compile { #[command(flatten)] input: Input, #[arg(long)] output:PathBuf }, Validate { #[command(flatten)] input:Input }, List { #[command(flatten)] input:Input }, Search { #[command(flatten)] input:Input, #[arg(required=true)] pattern:Vec<String> }, Explain { #[command(flatten)] input:Input, name:String } }
#[derive(Args,Clone)] struct Input { #[arg(long,value_enum)] shell:Shell, #[arg(long,default_value="auto",value_enum)] platform:PlatformArg, #[arg(long,default_value="auto")] distro:DistroArg, #[arg(long,default_value="auto")] environment:EnvironmentArg, #[arg(long)] source:PathBuf, #[arg(long)] no_local:bool, #[arg(long,conflicts_with="no_shortcut_map")] shortcut_map:Option<PathBuf>, #[arg(long)] no_shortcut_map:bool }
fn main()->ExitCode { let cli=Cli::parse();let (input,action)=match cli.command {Command::Compile{input,output}=>(input,Action::Compile(output)),Command::Validate{input}=>(input,Action::Validate),Command::List{input}=>(input,Action::List),Command::Search{input,pattern}=>(input,Action::Search(pattern)),Command::Explain{input,name}=>(input,Action::Explain(name))};let context=Context::resolve(input.shell,input.platform,input.distro,input.environment);let options=CompileOptions{context,source:input.source,local:!input.no_local,shortcut_map:if input.no_shortcut_map{None}else{input.shortcut_map}};let model=match compile_model(&options){Ok(x)=>x,Err(d)=>{print_diags(&d);return ExitCode::FAILURE}};print_diags(&model.diagnostics);match action {Action::Validate=>ExitCode::SUCCESS,Action::List=>{for d in &model.definitions{println!("{}",d.name)}ExitCode::SUCCESS},Action::Search(pattern)=>{let pat=pattern.iter().map(|x|x.to_ascii_lowercase()).collect::<Vec<_>>();for d in &model.definitions{if pat.iter().all(|p|d.name.to_ascii_lowercase().contains(p)){println!("{}\t{}",d.name,d.span)}}ExitCode::SUCCESS},Action::Explain(name)=>{match model.definitions.iter().find(|d|d.name==name){Some(d)=>{println!("name: {}\nsource: {}\nmode: {}",d.name,d.span,if d.legacy{"legacy-cmd"}else{"portable"});ExitCode::SUCCESS},None=>{eprintln!("aliasc: definition `{name}` is not active for this target context");ExitCode::FAILURE}}},Action::Compile(output)=>{let generated=match backend::generate(&model.context,&model.definitions){Ok(x)=>x,Err(d)=>{print_diags(&d);return ExitCode::FAILURE}};match manifest::write_outputs(&output,&model,generated){Ok(())=>ExitCode::SUCCESS,Err(e)=>{eprintln!("aliasc: {}: {e}",output.display());ExitCode::FAILURE}}}} }
enum Action{Compile(PathBuf),Validate,List,Search(Vec<String>),Explain(String)}
fn print_diags(diags:&[aliasc::Diagnostic]){for d in diags{eprintln!("{d}");}}
