use crate::{backend::Generated, Compilation};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::{env, fs, io, path::{Path, PathBuf}};

#[derive(Serialize)] struct Manifest<'a> { compiler: Compiler, target: &'a crate::Context, source: &'a Path, includes: Vec<&'a Path>, alias_local: Option<&'a Path>, shortcut_map: Option<&'a Path>, inputs: &'a [crate::resolver::TrackedInput], outputs: Vec<Output> }
#[derive(Serialize)] struct Compiler { path: PathBuf, version: String }
#[derive(Serialize)] struct Output { path: PathBuf, content_hash: String }
pub fn write_outputs(output:&Path, model:&Compilation, generated:Generated)->io::Result<()> { let output=if output.is_absolute(){output.to_path_buf()}else{env::current_dir()?.join(output)}; let mut outputs=Vec::new(); let mut primary=generated.primary; let sibling_data=generated.sibling.map(|(name,text)|(output.parent().unwrap_or(Path::new(".")).join(name),text)); if let Some((sibling,_))=&sibling_data { let quoted=sibling.to_string_lossy().replace('"', "\\\""); primary=primary.replace("%~dp0aliasc-runtime.cmd",&quoted); } write_atomic(&output,&primary)?;outputs.push(Output{path:output.clone(),content_hash:hash(&primary)});if let Some((sibling,text))=sibling_data{write_atomic(&sibling,&text)?;outputs.push(Output{path:sibling,content_hash:hash(&text)});}let manifest=Manifest{compiler:Compiler{path:env::current_exe().unwrap_or_else(|_|PathBuf::from("aliasc")),version:env!("ALIASC_VERSION").into()},target:&model.context,source:&model.source,includes:model.includes.iter().map(|x|x.as_path()).collect(),alias_local:model.local_path.as_deref(),shortcut_map:model.shortcut_map.as_deref(),inputs:&model.tracked_inputs,outputs};let data=serde_json::to_vec_pretty(&manifest).expect("serializable manifest");let mut p=output.as_os_str().to_owned();p.push(".manifest.json");write_atomic(Path::new(&p),std::str::from_utf8(&data).expect("json utf8")) }
fn write_atomic(path:&Path,text:&str)->io::Result<()> { let parent=path.parent().unwrap_or(Path::new("."));fs::create_dir_all(parent)?;let temp=parent.join(format!(".{}.{}.tmp",path.file_name().and_then(|x|x.to_str()).unwrap_or("aliasc"),std::process::id()));fs::write(&temp,text)?;match fs::rename(&temp,path){Ok(())=>Ok(()),Err(e)=>{let _=fs::remove_file(path);fs::rename(temp,path).map_err(|_|e)}} }
fn hash(s:&str)->String{format!("{:x}",Sha256::digest(s.as_bytes()))}
