use crate::{context::{known_section, shell_section}, default_shortcut_map, dsl::{self, ArgumentSegment, CommandTemplate, Diagnostic, RawDefinition, Severity, SourceSpan, Template}, Compilation, CompileOptions, Definition};
use serde::Serialize;
use std::{collections::HashMap, fs, path::{Path, PathBuf}, time::UNIX_EPOCH};

#[derive(Clone, Debug, Serialize)]
pub struct TrackedInput { pub path: PathBuf, pub exists: bool, pub mtime_ns: Option<u128>, pub size: Option<u64> }
struct State<'a> { options:&'a CompileOptions, raw:Vec<RawDefinition>, diagnostics:Vec<Diagnostic>, includes:Vec<PathBuf>, tracked:Vec<TrackedInput>, local_seen:bool }

pub fn resolve(options:&CompileOptions)->Result<Compilation,Vec<Diagnostic>> {
    let source=absolute(&options.source); let mut st=State{options,raw:Vec::new(),diagnostics:Vec::new(),includes:Vec::new(),tracked:Vec::new(),local_seen:false};
    visit(&mut st,&source,&mut Vec::new(),false,None);
    let local=source.parent().unwrap_or(Path::new(".")).join("alias.local");
    if options.local { if !st.local_seen { visit(&mut st,&local,&mut Vec::new(),true,None); } else { track(&mut st,&local); } }
    let shortcut=options.shortcut_map.clone().or_else(||Some(default_shortcut_map(&source)));
    if let Some(path)=&shortcut { add_shortcuts(&mut st,path); }
    let mut resolved:Vec<Definition>=Vec::new(); let mut positions=HashMap::new();
    for raw in st.raw {
        let active=raw.local || raw.section.as_ref().is_some_and(|s|st.options.context.section_active(s)); if !active {continue}
        let mut legacy=raw.section.as_ref().is_some_and(|x|x.eq_ignore_ascii_case("windows"));
        let result=if legacy && !(raw.body.trim_start().starts_with("SetEnv(") || raw.body.trim_start().starts_with("UnsetEnv(")) { Ok(Template::LegacyCmdTemplate(raw.body.clone())) } else { legacy=false; dsl::parse_template(&raw.body,&raw.span,&raw.include_stack) };
        match result { Ok(mut template)=>{annotate_first_available(&mut template,&raw.name);let d=Definition{name:raw.name,template,span:raw.span,legacy,context:st.options.context.clone()};let key=d.name.to_ascii_lowercase();if let Some(i)=positions.get(&key).copied(){resolved[i]=d}else{positions.insert(key,resolved.len());resolved.push(d)}}, Err(e)=>st.diagnostics.push(e) }
    }
fn annotate_first_available(template:&mut Template,name:&str){match template{Template::Command(command)=>{command.bypass_shell_function=first_command_word(command).is_some_and(|candidate_name|candidate_name.eq_ignore_ascii_case(name));},Template::WithEnv{body:Some(command),..}=>{command.bypass_shell_function=first_command_word(command).is_some_and(|candidate_name|candidate_name.eq_ignore_ascii_case(name));},Template::FirstAvailable(candidates)=>{for candidate in candidates{candidate.bypass_shell_function=first_command_word(candidate).is_some_and(|candidate_name|candidate_name.eq_ignore_ascii_case(name));}},_=>{}}}
fn first_command_word(candidate:&CommandTemplate)->Option<&str>{let invocation=candidate.pipeline.commands.first()?;let argument=invocation.arguments.first()?;match argument.segments.as_slice(){[ArgumentSegment::Literal(value)]=>Some(value.as_str()),_=>None}}
    if st.diagnostics.iter().any(|x|x.severity==Severity::Error){return Err(st.diagnostics)}

    Ok(Compilation{definitions:resolved,diagnostics:st.diagnostics,tracked_inputs:dedup_tracked(st.tracked),includes:st.includes,source,local_path:if options.local{Some(local)}else{None},shortcut_map:shortcut,context:options.context.clone()})
}
fn visit(st:&mut State<'_>,path:&Path,stack:&mut Vec<PathBuf>,local:bool,origin:Option<SourceSpan>){let path=absolute(path);if stack.contains(&path){let mut chain=stack.clone();chain.push(path.clone());st.diagnostics.push(Diagnostic::error(origin.unwrap_or(SourceSpan{file:path.clone(),line:1,column:1}),"include cycle detected",chain));return}track(st,&path);let text=match fs::read_to_string(&path){Ok(v)=>v,Err(_)=>{let warning_span=origin.unwrap_or(SourceSpan{file:path.clone(),line:1,column:1});if stack.is_empty() && !local {st.diagnostics.push(Diagnostic::error(warning_span,format!("source `{}` does not exist",path.display()),Vec::new()));}else if !local{st.diagnostics.push(Diagnostic::warning(warning_span,format!("optional include `{}` does not exist",path.display()),stack.clone()));}return}};if local{st.local_seen=true}else if !stack.is_empty(){st.includes.push(path.clone())};stack.push(path.clone());let mut section:Option<String>=None;
 for(line_no,line)in text.lines().enumerate(){let trimmed=line.trim();let span=SourceSpan{file:path.clone(),line:line_no+1,column:line.find(|c:char|!c.is_whitespace()).unwrap_or(0)+1};if trimmed.is_empty()||trimmed.starts_with('#')||trimmed.starts_with(';'){continue}if trimmed.starts_with('[')&&trimmed.ends_with(']'){let name=trimmed[1..trimmed.len()-1].trim();if name.is_empty(){st.diagnostics.push(Diagnostic::error(span,"empty section name",stack.clone()));continue}section=Some(name.to_string());if shell_section(name){st.diagnostics.push(Diagnostic::warning(SourceSpan{file:path.clone(),line:line_no+1,column:1},format!("shell section [{name}] is unsupported in v2 and will not be emitted"),stack.clone()));}else if !known_section(name){st.diagnostics.push(Diagnostic::warning(SourceSpan{file:path.clone(),line:line_no+1,column:1},format!("unknown section [{name}] is inactive"),stack.clone()));}continue}if let Some(include)=parse_include(trimmed){let include_path=resolve_include(&path,&include);if include_path.file_name().is_some_and(|n|n=="alias.local") {track(st,&include_path);continue}if section.is_some(){st.diagnostics.push(Diagnostic::error(span,"include is only allowed at top level",stack.clone()));continue}visit(st,&include_path,stack,false,Some(span));continue}if trimmed.starts_with("include") {st.diagnostics.push(Diagnostic::error(span,"include must be include \"path\"",stack.clone()));continue}let Some((name,body))=trimmed.split_once('=')else{st.diagnostics.push(Diagnostic::error(span,"expected section, include, or name=body definition",stack.clone()));continue};let name=name.trim();if !dsl::valid_name(name){st.diagnostics.push(Diagnostic::error(span,format!("invalid definition name `{name}`"),stack.clone()));continue}if section.is_none()&&!local{st.diagnostics.push(Diagnostic::error(span,"definitions outside a section are only allowed in alias.local",stack.clone()));continue}st.raw.push(RawDefinition{name:name.into(),body:body.trim().into(),section:section.clone(),span,include_stack:stack.clone(),local});}stack.pop();}
fn parse_include(s:&str)->Option<String>{let x=s.strip_prefix("include")?.trim();if x.len()>=2&&x.starts_with('"')&&x.ends_with('"'){Some(x[1..x.len()-1].to_string())}else{None}}
fn resolve_include(parent:&Path,include:&str)->PathBuf{let p=PathBuf::from(include);if p.is_absolute(){p}else{parent.parent().unwrap_or(Path::new(".")).join(p)}}
fn absolute(path:&Path)->PathBuf{if path.is_absolute(){path.to_path_buf()}else{std::env::current_dir().unwrap_or_else(|_|PathBuf::from(".")).join(path)}}
fn track(st:&mut State<'_>,path:&Path){let p=absolute(path);let md=fs::metadata(&p).ok();let mtime_ns=md.as_ref().and_then(|m|m.modified().ok()).and_then(|t|t.duration_since(UNIX_EPOCH).ok()).map(|d|d.as_nanos());st.tracked.push(TrackedInput{path:p,exists:md.is_some(),mtime_ns,size:md.map(|m|m.len())});}
fn dedup_tracked(items:Vec<TrackedInput>)->Vec<TrackedInput>{let mut out=Vec::new();for x in items{if !out.iter().any(|y:&TrackedInput|y.path==x.path){out.push(x)}}out}
fn normalize_shortcut_yaml(text:&str)->String { text.lines().map(|line| { let Some(colon)=line.find(':') else { return line.to_string() }; let (prefix,value)=line.split_at(colon+1); let value=value.trim(); if value.starts_with('%') && !value.starts_with("'%") && !value.starts_with("\"%") { format!("{} '{}'",prefix,value.replace('\'',"''")) } else { line.to_string() } }).collect::<Vec<_>>().join("\n") }
fn add_shortcuts(st:&mut State<'_>,path:&Path){track(st,path);let Ok(text)=fs::read_to_string(path)else{return};let normalized=normalize_shortcut_yaml(&text);let value:serde_yaml::Value=match serde_yaml::from_str(&normalized){Ok(v)=>v,Err(e)=>{st.diagnostics.push(Diagnostic::error(SourceSpan{file:path.to_path_buf(),line:e.location().map(|x|x.line()).unwrap_or(1),column:e.location().map(|x|x.column()).unwrap_or(1)},format!("invalid ShortcutMap YAML: {e}"),Vec::new()));return}};let Some(root)=value.as_mapping()else{st.diagnostics.push(Diagnostic::error(SourceSpan{file:path.to_path_buf(),line:1,column:1},"ShortcutMap root must be a mapping",Vec::new()));return};for(group,prefix,verb)in [("Config","Edit","edt"),("History","Edit","edt"),("Log","View","less")]{let key=serde_yaml::Value::String(group.into());let Some(map)=root.get(&key)else{continue};let Some(map)=map.as_mapping()else{st.diagnostics.push(Diagnostic::error(SourceSpan{file:path.to_path_buf(),line:1,column:1},format!("ShortcutMap {group} must be a mapping"),Vec::new()));continue};for(k,v)in map {let(Some(n),Some(p))=(k.as_str(),v.as_str())else{st.diagnostics.push(Diagnostic::error(SourceSpan{file:path.to_path_buf(),line:1,column:1},format!("ShortcutMap {group} entries must be strings"),Vec::new()));continue};let name=format!("{prefix}{n}{group}");let span=SourceSpan{file:path.to_path_buf(),line:1,column:1};match dsl::parse_template(&format!("{verb} \"{p}\""),&span,&[]) {Ok(_)=>st.raw.insert(0,RawDefinition{name,body:format!("{verb} \"{p}\""),section:Some("Common".into()),span,include_stack:Vec::new(),local:false}),Err(_)=>{}}}}}
